export const SERVER_TYPING = "SERVER_TYPING"
export const SERVER_END_TYPING = "SERVER_END_TYPING"
export const USER_TYPING = "USER_TYPING"
export const USER_END_TYPING = "USER_END_TYPING"
export const QUICK_BUTTON_CLICK = "QUICK_BUTTON_CLICK"
export const SAVE_MESSAGE = "SAVE_MESSAGE"

export const REQUEST_CONVERSATION_ANALYTICS = "REQUEST_CONVERSATION_ANALYTICS"
export const RECEIVE_CONVERSATION_ANALYTICS = "RECEIVE_CONVERSATION_ANALYTICS"

export const REQUEST_CONVERSATION_DATASET = "REQUEST_CONVERSATION_DATASET"
export const RECEIVE_CONVERSATION_DATASET = "RECEIVE_CONVERSATION_DATASET"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGOUT = "LOGOUT"

export const TOGGLE_NAVBAR = "TOGGLE_NAVBAR"
export const CONTACT_SUCCESS = "CONTACT_SUCCESS"
export const CONTACT_REQUEST = "CONTACT_REQUEST"
export const CONTACT_FAILURE = "CONTACT_FAILURE"

export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS"
export const SUBMIT_REQUEST = "SUBMIT_REQUEST"
export const SUBMIT_FAILURE = "SUBMIT_FAILURE"

