export const SERVER_TYPING = "SERVER_TYPING"
export const SERVER_END_TYPING = "SERVER_END_TYPING"
export const USER_TYPING = "USER_TYPING"
export const USER_END_TYPING = "USER_END_TYPING"
export const QUICK_BUTTON_CLICK = "QUICK_BUTTON_CLICK"
export const SAVE_MESSAGE = "SAVE_MESSAGE"

export const REQUEST_CONVERSATION_AVG = "REQUEST_CONVERSATION_ANALYTICS"
export const SUCCESS_CONVERSATION_AVG = "SUCCESS_CONVERSATION_ANALYTICS"
export const FAILURE_CONVERSATION_AVG = "FAILURE_CONVERSATION_ANALYTICS"

export const REQUEST_CONVERSATION_DATASET = "REQUEST_CONVERSATION_DATASET"
export const SUCCESS_CONVERSATION_DATASET = "SUCCESS_CONVERSATION_DATASET"
export const FAILURE_CONVERSATION_DATASET = "FAILURE_CONVERSATION_DATASET"

export const REQUEST_LOGIN = "REQUEST_LOGIN"
export const SUCCESS_LOGIN = "SUCCESS_LOGIN"
export const FAILURE_LOGIN = "FAILURE_LOGIN"

export const TOGGLE_NAVBAR = "TOGGLE_NAVBAR"
export const LOGOUT = "LOGOUT"

export const REQUEST_CONTACT = "REQUEST_CONTACT"
export const SUCCESS_CONTACT = "SUCCESS_CONTACT"
export const FAILURE_CONTACT = "FAILURE_CONTACT"

export const REQUEST_SUBSCRIBE = "REQUEST_SUBSCRIBE"
export const SUCCESS_SUBSCRIBE = "SUCCESS_SUBSCRIBE"
export const FAILURE_SUBSCRIBE = "FAILURE_SUBSCRIBE"

export const REQUEST_THREAD_LIST = "REQUEST_THREAD_LIST"
export const SUCCESS_THREAD_LIST = "SUCCESS_THREAD_LIST"
export const FAILURE_THREAD_LIST = "FAILURE_THREAD_LIST"

export const REQUEST_THREAD = "REQUEST_THREAD"
export const SUCCESS_FETCH_THREAD = "SUCCESS_FETCH_THREAD"
export const FAILURE_FETCH_THREAD = "FAILURE_FETCH_THREAD"

