
export const TOGGLE_NAVBAR = "TOGGLE_NAVBAR"

export const REQUEST_CONTACT = "REQUEST_CONTACT"
export const SUCCESS_CONTACT = "SUCCESS_CONTACT"
export const FAILURE_CONTACT = "FAILURE_CONTACT"

export const REQUEST_SUBSCRIBE = "REQUEST_SUBSCRIBE"
export const SUCCESS_SUBSCRIBE = "SUCCESS_SUBSCRIBE"
export const FAILURE_SUBSCRIBE = "FAILURE_SUBSCRIBE"
