export const sendMessageEndPoint = "/api/message"
export const contactEndPoint = "/api/contact"
export const subscribeEndPoint = "/api/subscribe"
export const facebookUrl = "https://www.facebook.com/narrafy"
export const twitterUrl = "https://www.twitter.com/narrafy"
export const mediumUrl = "https://www.medium.com/narrafy"